% Creates the homepage for the hardware injection output. LLO and LHO have
% their own homepages.
function homepageHTML2()
    path = getWebsiteLocation();
    server = getServerName();
    if (strcmp(server, 'L1'))
        host = 'LLO';
    else
        host = 'LHO';
    end
    title = sprintf('%s', 'Hardware Injections: ', host);
    text = sprintf('%s\n', ...
            '<!DOCTYPE html>', ...
            '<html>', ...
            '<head>', ...
                ['\t<title>', title, '</title>'], ...
                '<link rel="stylesheet" type="text/css" href="HWInjection.css"/>', ...
            '</head>', ...
            '<body>', ...
                '<div class = "header">', ...
                    '<h1>', ...
                        title, ...
                    '</h1>', ...
                '</div>', ...
                '<div class = "navBlock">', ...
                    '<table style="width:50%%">', ...
                        '<tr>', ...
                            '<th>Pulsar Navigation</th>', ...
                        '</tr>');
    for i = 0:14
        tableEntry = sprintf('<tr><td><a href="Pulsar%1$02d/Pulsar%1$02d.html">Pulsar %1$02d</a></td></tr>', i);
	text = [text, tableEntry];
    end
    ending = sprintf('%s', ...
	             '</table>', ...
                '</div>', ...   
	'<footer>Contact: eilam@umich.edu</footer>', ...
        '</body>', ...
        '</html>');
    text = [text, ending];

    filename = [path, '/HWInjection.html'];
    disp(['Creating file ', filename]);
    fileID = fopen(filename, 'w');
    fprintf(fileID, text);
    fclose(fileID);
end
