% Stylesheet for the Pulsars' HTML pages
function pulsarCSS(path)
    text = sprintf('%s', '' ,...
    '.header {\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
    '}\n', ...
    'h1 {\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
    '}\n', ...
    'h2 {\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
    '}\n', ...
    '.text {\n', ...
	    'padding-top: 25px;\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
    '}\n', ...
    'h4 {\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
    '}\n', ...
    '.date {\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
    '}\n', ...
    '.data {\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
    '}\n', ...
    '.pulsarNav {\n', ...
	    'padding-top: 10px;\n', ...
            'text-align: center;\n', ...
            'font-family: Helvetica;\n', ...
	    'padding-bottom: 0px;\n', ...
    '}\n', ...
    'ul {\n', ...
            '-webkit-padding-start: 0px;\n', ...
    '}\n');

    filename = [path, 'pulsar.css'];
    fileID = fopen(filename, 'w');
    fprintf(fileID, text);
    fclose(fileID);
end
